spring:
  application:
    name: Admin
    version: 1.0

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/db_test
    username: root
    password: root


#debug: true
mybatis-plus:
  type-aliases-package: com.example.demo.**.pojo
  mapper-locations: classpath*:com/example/demo/repository/mapper/mapper/**/*.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

app:
  security:
    session:
      expires-in: 3600
      maximum-sessions: 1

    account:
      password-pattern: "[a-zA-Z0-9_-]{6,10}"
      username-pattern: "[a-zA-Z0-9_-]{6,10}"

    auth:
      permit-all-uri:
        -
      anonymous-uri:
        -