spring:
  application:
    name: Admin
    version: 1.0
  # 所有前端序列化数据
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

app:
  server:
    host: 0.0.0.0
    http-port: 8080
    https-port: 8443
  common:
    charset: UTF-8
  db:
    enable-init: false
  security:
    jwt:
      secret: "qweoimjaosijd_da1udad"
    session:
      expires-in: 1h
      maximum-sessions: 1
    white-list-uri:
      - /debug/**
      - GET /
      - GET /index.html
      - GET /favicon.ico
            # 以下为swagger knife4j
      - GET /v3/api-docs/*
      - GET /doc.html
      - GET /webjars/**

---
# 数据库相关
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/admin_template
    username: root
    password: root

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: redis
---

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.demo.api
      display-name: 默认文档
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 模型
  documents:
    - group: 'default'
  production: false

mybatis-plus:
  type-aliases-package: com.example.demo.**.pojo
  mapper-locations: classpath*:com/example/demo/repository/mapper/**/*.xml

server:
  servlet:
    encoding:
      charset: ${app.common.charset}
  error:
    whitelabel:
      enabled: false
  port: ${app.server.https-port}
  address: ${app.server.host}
    #  ssl:
    #    key-store: classpath:keystore.p12
    #    key-store-password: 123456
    #    key-store-type: PKCS12
    